#! /bin/bash
#
# Plamen Vasilev a.k.a Paco - p.vasileff@gmail.com
# Jakub Zemanek - zemanekj@vspj.cz
#

PROGNAME=`basename $0`
PROGPATH=`dirname $0`
REVISION=`echo '$Revision: 2.0 $' | sed -e 's/[^0-9.]//g'`


. $PROGPATH/utils.sh

print_usage() {
    echo -e "Usage: $PROGNAME -H <ip_address> [-w <number>] [-c <number>] [-C <community>]
[-P <snmp version>] [-U <username>] [-L <secLevel>] [-a <authproto>]
[-x <privproto>] [-A <authpassword>] [-X <privpassword>]"
    echo -e "\nOptions:"
    echo -e " -V, --version\n    Print version information"
    echo -e " -h, --help\n    Print detailed help screen"
    echo -e " -H, --hostname=ADDRESS\n    Host name od IP address"
    echo -e " -w, --warning=INTEGER\n    Warning treshold  (default 20)"
    echo -e " -c, --critical=INTEGER\n    Critical treshold (default 25)"
    echo -e " -C, --community=STRING\n    Optional community string for SNMP communication (default is public)"
    echo -e " -P, --protocol=[1|2c|3]\n    SNMP protocol version(default is 2c)"
    echo -e " -L, --seclevel=[noAuthNoPriv|authNoPriv|authPriv]\n    SNMPv3 securityLevel"
    echo -e " -a, --authproto=[MD5|SHA]\n    SNMPv3 auth proto"
    echo -e " -x, --privproto=[DES|AES]\n    SNMPv3 priv proto"
    echo -e " -U, --secname=USERNAME\n    SNMPv3 username"
    echo -e " -A, --authpassword=PASSWORD\n    SNMPv3 authentication password"
    echo -e " -X, --privpassword=PASSWORD\n    SNMPv3 privacy password"

echo "
This plugin uses the 'snmpwalk' command included with the NET-SNMP package.
if you don't have the package installed, you will need to download it from
http://net-snmp.sourceforge.net before you can use this plugin."
}

print_help() {
    print_revision $PROGNAME $REVISION
    echo ""
    echo "This plugin checks how many clients are connected to wireless"
    echo ""
    print_usage
    echo ""
    support
}

#Set default values
critical=25
warning=20
counter=0
community=""
protocol=""
secname=""
authproto=""
privproto=""
privpasswd=""
authpassword=""

#Process parameters
while test -n "$1"; do
        case "$1" in
                        --help)
                            print_help
                            exit $STATE_OK
                            ;;
                        -h)
                            print_help
                            exit $STATE_OK
                            ;;
                        --version)
                            print_revision $PROGNAME $REVISION
                            exit $STATE_OK
                            ;;
                        -V)
                            print_revision $PROGNAME $REVISION
                            exit $STATE_OK
                            ;;
                        -w)
                            warning=$2
                            shift
                            ;;
                        --warning*)
                            warning=" $(echo $1 | cut -d "=" -f 2)"
                            ;;
                            -c)
                            critical=$2
                            shift
                            ;;
                            --critical*)
                            critical=" $(echo $1 | cut -d "=" -f 2)"
                            ;;
                        -H)
                            Host=" $2"
                            shift
                            ;;
                        --hostname*)
                            Host=" $(echo $1 | cut -d "=" -f 2)"
                            ;;
                        -C)
                            community=" -c $2"
                            shift
                            ;;
                        --community*)
                            community=" -c $(echo $1 | cut -d "=" -f 2)"
                            ;;
                        -P)
                            protocol=" -v $2"
                            shift
                            ;;
                        --protocol*)
                            protocol=" -v $(echo $1 | cut -d "=" -f 2)"
                            ;;
                        -U)
                            secname=" -u $2"
                            shift
                            ;;
                        --secname*)
                            secname=" -u $(echo $1 | cut -d "=" -f 2)"
                            ;;
                        -a)
                            authproto=" -a $2"
                            shift
                            ;;
                        --authproto*)
                            authproto=" -a $(echo $1 | cut -d "=" -f 2)"
                            ;;
                        -x)
                            privproto=" -x $2"
                            shift
                            ;;
                        --privproto*)
                            privproto=" -x $(echo $1 | cut -d "=" -f 2)"
                            ;;
                        -A)
                            authpassword=" -A $2"
                            shift
                            ;;
                        --authpassword*)
                            authpassword=" -A $(echo $1 | cut -d "=" -f 2)"
                            ;;
                        -X)
                            privpasswd=" -X $2"
                            shift
                            ;;
                        --privpassword*)
                            privpasswd=" -X $(echo $1 | cut -d "=" -f 2)"
                            ;;
                        -L)
                            seclevel=" -l $2"
                            shift
                            ;;
                        --seclevel*)
                            seclevel=" -l $(echo $1 | cut -d "=" -f 2)"
                            ;;
                        *)
                            echo "Unknown argument: $1"
                            echo "Usage: $PROGNAME --help"
                            exit $STATE_UNKNOWN
                            ;;
        esac
        shift
done

#Host is not optional
if [ "$Host" == "" ]; then
    exit $STATE_UNKNOWN
fi

#Set default values
if [ "$protocol" == "" ]; then
    protocol=" -v 2c"
    community=" -c public"
fi


output=$(snmpwalk $community$authproto$authpassword$privpasswd$protocol$secname$seclevel$privproto -Ovq $Host 1.3.6.1.4.1.14988.1.1.1.2.1.3)
if [ $? -ne "0" ] ; then
    exit $STATE_CRITICAL
fi

noconnectedclients='No Such Object available on this agent at this OID'

if [[ $output == "$noconnectedclients" ]] ; then
        echo "CLIENTS - Connected 0 clients to the wireless|clients=0"
        exit $STATE_OK
fi

for i in $output
do
    let counter=counter+1
done


echo "CLIENTS - Connected $counter clients to the wireless|clients=$counter"

# Nagios Statements
# WARNING / CRITICAL / OK
if [ $counter -ge $critical ]
        then
        #echo CRITICAL
        exit $STATE_CRITICAL

elif [[ $counter -ge $warning ]]
        then
        #echo WARNING
        exit $STATE_WARNING

else
        #echo OK
        exit $STATE_OK
fi
